name: Drillionaire
favicon: null
layout_spectrum: 0.89
typography_spectrum: 0.99496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#053f64'
    - '#ef542b'
    - '#fec936'
    - '#4ebe68'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
