typography_spectrum: 0.99496
color:
  brandColors:
    - '#ffffff'
    - '#053f64'
    - '#ef542b'
    - '#fec936'
    - '#4ebe68'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89
analytics:
  google: null
  facebook: null
  twitter: null
name: Drillionaire
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hello World.
purpose: []
